//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matlab
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeValues
    {
        public int id { get; set; }
        public int idWord { get; set; }
        public Nullable<double> K_MIN { get; set; }
        public Nullable<double> K_MAX { get; set; }
        public Nullable<double> K_Round { get; set; }
        public Nullable<double> S_MIN { get; set; }
        public Nullable<double> S_MAX { get; set; }
        public Nullable<double> S_Round { get; set; }
        public Nullable<double> NF_MIN { get; set; }
        public Nullable<double> NF_MAX { get; set; }
        public Nullable<double> NF_Round { get; set; }
        public Nullable<double> Lenght_MIN { get; set; }
        public Nullable<double> Lenght_MAX { get; set; }
        public Nullable<double> Lenght_Round { get; set; }
    
        public virtual Words Words { get; set; }
    }
}
